---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.nano
      ami: ami-f4cc1de2  # Ubuntu 16.04 LTS
      #ami: ami-0400a1104d5b9caa1 # Ubuntu 18.04 LTS hvm:ebs-ssd
      keypair: rg-instances # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         group: rg-sg-default  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: subnet-0xxxxxxx
         assign_public_ip: yes
      register: ec2
